version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
    - 1.5.0
  - dependency-name: org.jetbrains.intellij
    versions:
    - 0.7.0
    - 0.7.1
    - 0.7.2
    - 0.7.3
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mkdocs-material
    versions:
    - 6.2.6
    - 6.2.7
    - 7.0.3
    - 7.0.7
    - 7.1.2
    - 7.1.3
