[versions]
# libraries
annotations = "26.0.2"
junit = "6.0.0"
opentest4j = "1.3.0"
# plugins
kotlin = "2.2.0"
changelog = "2.2.0"
gradleIntelliJPlugin = "2.10.5"
qodana = "0.1.13"
kover = "0.9.3"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j"}

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
